package com.kasjan.common.event;

public enum EventType {
  ACCOUNT_CREATED,

  ORDER_CREATED,

  PAYMENT_AUTHORIZED,
  PAYMENT_VALIDATION_FAILED,
  PAYMENT_VOIDED,

  RESTAURANT_AVAILABILITY_CHECKED,
  RESTAURANT_AVAILABILITY_CHECK_FAILED,

  COURIER_ASSIGNED,
  COURIER_UNASSIGNED,
  COURIER_TOOK_ORDER,
  ORDER_DELIVERED,
  ORDER_CANCEL_REQUESTED,
  ORDER_CANCELED,
  MANUAL_REVIEW_REQUESTED,
}
