package com.kasyan.common.event;

public enum EventType {
  ORDER_CREATED,
  PAYMENT_AUTHORIZED,
  PAYMENT_VALIDATION_FAILED,
  RESTAURANT_AVAILABILITY_CHECKED,
  COURIER_ASSIGNED,
  COURIER_TOOK_ORDER
}
